### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by XJLZ** [hua1995116/google-translate-open-api#13]
```
const translate = require('google-translate-open-api');
let result = translate(`I'm fine.`, {
  tld: "cn",
  to: "zh-CN",
});
let data = result.data[0];
```
使用Nodejs 运行报错：
```
let result = translate(`I'm fine.`, {
             ^
TypeError: translate is not a function
    at Object.<anonymous> (D:\NodeProjects\code\translation.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by hua1995116** [comment]
本包采用的 es modules 方式，你可以通过下面的形式引入。
For commonJS
```
const translate = require('google-translate-open-api').default;
```

**Comment by XJLZ** [comment]
多谢，问题解决了
