### ISSUE TITLE
TypeError: translate is not a function

### ISSUE THREAD

**Issue by flyeven** [hua1995116/google-translate-open-api#24]
```
const result = await translate(`I'm fine.`, {
                     ^

TypeError: translate is not a function
```

运行测试代码，出现如上问题。怎么解？

```
import translate from 'google-translate-open-api';
const result = await translate(`I'm fine.`, {
  tld: "cn",
  to: "zh-CN",
});
const data = result.data[0];
```

**Comment by flyeven** [comment]
node 版本 14，运行 google bing api 都没为题。单独创建npm项目，只添加  google-translate-open-api ，也是上述问题。

```
$ node -v
v14.15.4

const translate = require('@vitalets/google-translate-api');

import pkg from 'bing-translate-api';
const { translate } = pkg;
```

**Comment by hua1995116** [comment]
我是用 ts-node 运行的

**Comment by flyeven** [comment]
我这怎么都不行呢，gitbash 下 和 ps 下都是错误。

```
PS D:\Programming\translate> ts-node index.js
TypeError: translate is not a function
    at file:///D:/Programming/translate/index.js:32:22
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at Loader.import (internal/modules/esm/loader.js:166:24)
    at Object.loadESM (internal/process/esm_loader.js:68:5)
PS D:\Programming\translate> node index.js
file:///D:/Programming/translate/index.js:32
const result = await translate(`I'm fine.`, {
                     ^

TypeError: translate is not a function
    at file:///D:/Programming/translate/index.js:32:22
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

或者就是：

```
$ ts-node index.mjs
ReferenceError: require is not defined
    at file:///D:/Programming/translate/index.mjs:1:19
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at Loader.import (internal/modules/esm/loader.js:166:24)
    at Object.loadESM (internal/process/esm_loader.js:68:5)
```

**Comment by heliang0915** [comment]
我是将这句 const result = await translate(`I'm fine.`, {
  tld: "cn",
  to: "zh-CN",
});
const data = result.data[0];   包在一个async函数中 ,

然后调用这个函数执行并调用它的then方法
